<a href="https://colab.research.google.com/github/amyxue-svg/MSSP6070/blob/main/Modules/Week4/Participation_Activity_Week_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
%run '/content/drive/MyDrive/MSSP 6070/Google_connection.py'

Changed directory to: /content/MSSP6070

In [4]:
import numpy as np
import pandas as pd
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
pd.options.display.max_rows = 20
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)

In [7]:
df = pd.read_csv('/content/drive/MyDrive/MSSP 6070/Modules/Week 4/parsed.csv')

2a

In [20]:
mb = df["magType"]=="mb"
Japan = df["place"].str.contains("Japan")
japanmb = df[Japan & mb]
japanmb["mag"].quantile(0.95)

np.float64(5.119999999999999)

2b

In [26]:
Indonesia = df["place"].str.contains("Indonesia")
Indonesia = df[Indonesia]
Indonesia["tsunami"].value_counts()
tsunami_percentage = Indonesia["tsunami"].value_counts()[1]/len(Indonesia)
print(tsunami_percentage)

0.23129251700680273

2c

In [27]:
Nevada = df["place"].str.contains("Nevada")
Nevada.describe()

count      9332
unique        2
top       False
freq       8655
Name: place, dtype: object

2d

In [66]:
Ring_of_fire = ("Bolivia|Chile|Ecuador|Peru|Costa Rica|Guatemala|Mexico|Japan|Philippines|Indonesia|New Zealand|Antarctic|Canada|Fiji|Alaska|Washington|California|Russia|Taiwan|Tonga|Kermadec Islands")
df["Ring_of_fire"] = df["parsed_place"].str.contains(Ring_of_fire) & ~df["parsed_place"].str.contains("New Mexico")
df[["place","Ring_of_fire"]].head()

                   place  Ring_of_fire
0  9km NE of Aguanga, CA          True
1  9km NE of Aguanga, CA          True
2  8km NE of Aguanga, CA          True
3  9km NE of Aguanga, CA          True
4  10km NW of Avenal, CA          True

2e

In [55]:
df["Ring_of_fire"].value_counts()

Ring_of_fire
True     7188
False    2144
Name: count, dtype: int64

2f

In [64]:
tsunami_Ring_of_fire = df[df[Ring_of_fire]]["tsunami"].value_counts()
print(tsunami_Ring_of_fire)

tsunami
0    4383
1      43
Name: count, dtype: int64